apiVersion: v2
name: gateway-api
description: Kubernetes Gateway API. Replace your ingress to the native Kubernetes Gateway API.
type: application
version: 0.2.0
appVersion: 1.0.0
home: http://charts.cdnn.host/
sources:
  - https://github.com/dev2prod-hub/gateway-api-chart/tree/main/charts/gateway-api
keywords:
  - gateway-api
  - networking
  - Kubernetes
  - ingress
maintainers:
  - name: dev2prod
    email: k@kazakov.xyz
    url: https://cdnn.cloud
  - name: Kirill Kazakov
    email: k@kazakov.xyz
    url: https://kazakov.xyz
icon: https://avatars.githubusercontent.com/u/191972069?s=96&v=4
dependencies: [] # Optional dependencies if applicable
