apiVersion: v2
name: gateway-api
description: Kubernetes Gateway API - Infrastructure Layer. Replace your ingress to the native Kubernetes Gateway API.
type: application
version: 1.0.5
appVersion: 1.0.0
home: https://charts.cdnn.host/
sources:
  - https://github.com/dev2prod-hub/gateway-api-chart/tree/main/charts/gateway-api
keywords:
  - gateway-api
  - gateway api helm chart
  - helm
  - helm chart
  - networking
  - Kubernetes
  - ingress
maintainers:
  - name: dev2prod
    email: k@kazakov.xyz
    url: https://cdnn.cloud
  - name: Kirill Kazakov
    email: k@kazakov.xyz
    url: https://kazakov.xyz
icon: https://avatars.githubusercontent.com/u/191972069?s=96&v=4
dependencies: [] # Optional dependencies if applicable
