global:
  labels:
    part-of: "gateway-api"

gatewayClass:
  enabled: true
  name: envoy-gateway # Optional
  labels: # Optional
    stage: fixture-testing
  annotations: # Optional
    stage: fixture-testing

  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  description: "This is a custom GatewayClass for Envoy" # Optional
  parametersRef: # Optional
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: proxy-config
    namespace: envoy-gateway-system
  infrastructure: # Optional. v1.4.1+ experimental
    labels:
      infra: envoy
    annotations:
      infra: envoy

gateway:
  enabled: true
  name: envoy-gateway # Optional
  gatewayClassName: envoy-gateway # Optional
  annotations:
    stage: fixture-testing
  infrastructure: # Optional. v1.4.1+ experimental
    labels:
      infra: envoy-gw
    annotations:
      infra: envoy-gw
    parametersRef:
      group: gateway.envoyproxy.io
      kind: GatewayInfrastructureConfig
      name: gw-infra-config
      namespace: envoy-gateway-system

  listeners:
    - name: api-backend-https
      protocol: HTTPS
      port: 443
      hostname: api.mydomain.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: api-mydomain-com-tls
            kind: Certificate # v1.4.1 support
          - name: api-mydomain-com-secret
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
      extraSpec:
        addresses:
          - type: IPAddress
            value: 10.1.2.3

  extraSpec: # Optional. Setup additional spec fields for the Gateway object
    addresses:
      - type: IPAddress
        value: 10.1.2.3
