{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name | default (include "gateway-api.fullname" .) | quote }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
    {{- with .Values.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gateway.annotations }}
  annotations: {{ . | toYaml | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName | default (include "gateway-api.fullname" .) | quote }}
  {{- with .Values.gateway.infrastructure }}
  infrastructure:
    {{- with .labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .parametersRef }}
    parametersRef:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- with .Values.gateway.extraSpec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  listeners:
  {{- range .Values.gateway.listeners }}
  - name: {{ .name }}
    protocol: {{ .protocol }}
    port: {{ .port }}
    {{- if .hostname }}
    hostname: {{ .hostname | quote }}
    {{- end }}
    {{- with .allowedRoutes }}
    allowedRoutes:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .tls }}
    tls:
      mode: {{ .tls.mode }}
      {{- with .tls.certificateRefs}}
      certificateRefs:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .extraSpec }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
