apiVersion: v2
name: gateway-api-routes
description: Kubernetes Gateway routes. Part of the Gateway API charts. Replace your ingress to the native Kubernetes Gateway API.
type: application
version: 1.0.1
appVersion: 1.0.0
home: https://charts.cdnn.host/
sources:
  - https://github.com/dev2prod-hub/gateway-api-chart/tree/main/charts/gateway-api-routes
keywords:
  - gateway-api-routes
  - networking
  - Kubernetes
  - ingress
maintainers:
  - name: dev2prod
    email: k@kazakov.xyz
    url: https://cdnn.cloud
  - name: Kirill Kazakov
    email: k@kazakov.xyz
    url: https://kazakov.xyz
icon: https://avatars.githubusercontent.com/u/191972069?s=96&v=4
dependencies: [] # Optional dependencies if applicable
